// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace UserStories.AcceptanceTest.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("Creates a new customer", SourceFile="Features\\NewCustomer.feature", SourceLine=0)]
    public partial class CreatesANewCustomerFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "NewCustomer.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Creates a new customer", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("The user can creates a new customer", SourceLine=2)]
        public virtual void TheUserCanCreatesANewCustomer()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("The user can creates a new customer", ((string[])(null)));
#line 3
this.ScenarioSetup(scenarioInfo);
#line 4
 testRunner.Given("The user enters to the home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 5
 testRunner.And("The user logs with a valid user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 6
 testRunner.When("The user goes to the new customer page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 7
 testRunner.And("The user creates a new customer with parameters \'Juan\', \'15121990\', \'Male\', \'Plaz" +
                    "a Catalunya\', \'Barcelona\', \'Barcelona\', \'123456\', \'666123444\', \'111222333\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 8
 testRunner.And("The user clicks the submit button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 9
 testRunner.Then("The customer with parameters \'Juan\', \'15121990\', \'Male\', \'Plaza Catalunya\', \'Barc" +
                    "elona\', \'Barcelona\', \'123456\', \'666123444\' has been created", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 10
 testRunner.And("The system dispose the web driver", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        public virtual void TheUserTriesToCreateANewCustomerWithEmptyParameters(string name, string date, string gender, string address, string city, string state, string pin, string mobile, string password, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("The user tries to create a new customer with empty parameters", exampleTags);
#line 12
this.ScenarioSetup(scenarioInfo);
#line 13
 testRunner.Given("The user enters to the home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 14
 testRunner.And("The user logs with a valid user", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 15
 testRunner.When("The user goes to the new customer page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 16
 testRunner.And(string.Format("The user creates a new customer with parameters \'{0}\', \'{1}\', \'{2}\', \'{3}\', \'{4}\'" +
                        ", \'{5}\', \'{6}\', \'{7}\', \'{8}\'", name, date, gender, address, city, state, pin, mobile, password), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 17
 testRunner.And("The user clicks the submit button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 18
 testRunner.Then("The customer cannot be created", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 19
 testRunner.And("The system dispose the web driver", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("The user tries to create a new customer with empty parameters, Variant 0", SourceLine=22)]
        public virtual void TheUserTriesToCreateANewCustomerWithEmptyParameters_Variant0()
        {
            this.TheUserTriesToCreateANewCustomerWithEmptyParameters("empty", "15121990", "Male", "Plaza Catalunya", "Barcelona", "Barcelona", "123456", "666123444", "111222333", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("The user tries to create a new customer with empty parameters, Variant 1", SourceLine=22)]
        public virtual void TheUserTriesToCreateANewCustomerWithEmptyParameters_Variant1()
        {
            this.TheUserTriesToCreateANewCustomerWithEmptyParameters("Juan", "empty", "Male", "Plaza Catalunya", "Barcelona", "Barcelona", "123456", "666123444", "111222333", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("The user tries to create a new customer with empty parameters, Variant 2", SourceLine=22)]
        public virtual void TheUserTriesToCreateANewCustomerWithEmptyParameters_Variant2()
        {
            this.TheUserTriesToCreateANewCustomerWithEmptyParameters("Juan", "15121990", "Male", "empty", "Barcelona", "Barcelona", "123456", "666123444", "111222333", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("The user tries to create a new customer with empty parameters, Variant 3", SourceLine=22)]
        public virtual void TheUserTriesToCreateANewCustomerWithEmptyParameters_Variant3()
        {
            this.TheUserTriesToCreateANewCustomerWithEmptyParameters("Juan", "15121990", "Male", "Plaza Catalunya", "empty", "Barcelona", "123456", "666123444", "111222333", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("The user tries to create a new customer with empty parameters, Variant 4", SourceLine=22)]
        public virtual void TheUserTriesToCreateANewCustomerWithEmptyParameters_Variant4()
        {
            this.TheUserTriesToCreateANewCustomerWithEmptyParameters("Juan", "15121990", "Male", "Plaza Catalunya", "Barcelona", "empty", "123456", "666123444", "111222333", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("The user tries to create a new customer with empty parameters, Variant 5", SourceLine=22)]
        public virtual void TheUserTriesToCreateANewCustomerWithEmptyParameters_Variant5()
        {
            this.TheUserTriesToCreateANewCustomerWithEmptyParameters("Juan", "15121990", "Male", "Plaza Catalunya", "Barcelona", "Barcelona", "empty", "666123444", "111222333", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("The user tries to create a new customer with empty parameters, Variant 6", SourceLine=22)]
        public virtual void TheUserTriesToCreateANewCustomerWithEmptyParameters_Variant6()
        {
            this.TheUserTriesToCreateANewCustomerWithEmptyParameters("Juan", "15121990", "Male", "Plaza Catalunya", "Barcelona", "Barcelona", "123456", "empty", "111222333", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("The user tries to create a new customer with empty parameters, Variant 7", SourceLine=22)]
        public virtual void TheUserTriesToCreateANewCustomerWithEmptyParameters_Variant7()
        {
            this.TheUserTriesToCreateANewCustomerWithEmptyParameters("Juan", "15121990", "Male", "Plaza Catalunya", "Barcelona", "Barcelona", "123456", "666123444", "empty", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.TestRunCleanup()]
        public virtual void TestRunCleanup()
        {
            TechTalk.SpecFlow.TestRunnerManager.GetTestRunner().OnTestRunEnd();
        }
    }
}
#pragma warning restore
#endregion
